# Generated by Django 3.2 on 2021-04-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='builtupArea',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='carpetArea',
            field=models.IntegerField(),
        ),
    ]
