# Generated by Django 3.2 on 2021-04-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_bedrooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='descripting',
            new_name='description',
        ),
    ]
